# Generated by Django 3.2.3 on 2021-05-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(verbose_name='Дата')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('distance', models.FloatField(verbose_name='Расстояние')),
            ],
        ),
    ]
